### ISSUE TITLE
Loose control after HASS Update 2024.8.1

### ISSUE THREAD

**Issue by Sonsi79** [elupus/gardena-bluetooth#14]
Since Update to HASS 2024.8.1 i loose control to the switch and all settings.
Only Battery-State ist available. 

I try to pair the device with Gardena BT App and there anything works fine.
Reset of der device and repair didn't fix the error in HASS.

Anyone the same error and maybe a fix for it?

<img width="366" alt="Bildschirmfoto 2024-08-12 um 14 31 10" src="https://github.com/user-attachments/assets/c0f882ba-cb47-496d-9f4d-63b1d3cdafcd">

**Comment by elupus** [comment]
Anything in logs?

**Comment by Sonsi79** [comment]
> Anything in logs?

Im sorry no logs or errors :-(

**Comment by Sonsi79** [comment]
Oh m sorry there was an error today.

Logger: homeassistant.components.gardena_bluetooth
Quelle: helpers/update_coordinator.py:360
Integration: Gardena Bluetooth (Dokumentation, Probleme)
Erstmals aufgetreten: 11. August 2024 um 16:39:48 (1 Vorkommnisse)
Zuletzt protokolliert: 11. August 2024 um 16:39:48

Timeout fetching Gardena Bluetooth Data Update Coordinator data

**Comment by Sonsi79** [comment]
Strange, after few restarts all entities are back again :-)
