### ISSUE TITLE
Quick questions on this upcoming integration

### ISSUE THREAD

**Issue by gavinpbennett** [elupus/gardena-bluetooth#3]
Thanks for your effort with this upcoming integration. I am shopping for a robot lawn mower (I know this is only for water control right now).
Gardena smart system is a bit confusing. Will this integration work with the water control unit that can be setup and controlled via Bluetooth only, or is the smart system hub also needed? 
From Gardena: "Unfortunately, here in NZ & AU, the smart technology in the Robotic Lawnmowers runs off the same digital radio signals used by Police force and Military."
I am hoping that I could help you to add lawn mower control to this integration at a later date.  I have not yet purchased a lawn mower, HA integration is part of my wish list for a device.

**Comment by elupus** [comment]
This is for the bluetooth based water control unit. No hub is needed for that unit.

I just found out the lawnmowers are using some Husqvarna Group extra protocol on top of bluetooth. So they are much more complex to support. It should be possible, but nothing I will be able to work on since i dont own one.

I will review patches and i think i would make sense to add support for it.

**Comment by larsvinc** [comment]
@gavinpbennett : I have looked at the same. I have a bluetooth lawn mower (gardena minimo) that I would happily want to control using bluetooth. 

@elupus how would I start looking into the protocol? Did you find any documentation regarding this extra protocol?

**Comment by elupus** [comment]
I wrote some thoughts here: https://community.home-assistant.io/t/gardena-bluetooth-lawn-mower/400399/7?u=elupus and here https://community.home-assistant.io/t/gardena-bluetooth-lawn-mower/400399/28?u=elupus

**Comment by andyb2000** [comment]
Just to add a "me too" to this, I own the Flymo Easilife Go 500 (Which is based around Husqvarna circuit boards, etc) which is bluetooth BLE controlled via app. I'm trying the discover but haven't had time to decipher the BLE characteristics attached. Hoping to try the connect/discover (and using nRF logging) to get info and see if I can adapt a PR to help add it to this great project.

**Comment by elupus** [comment]
Not really relevent anymore. Closing

**Comment by lasry1** [comment]
> Just to add a "me too" to this, I own the Flymo Easilife Go 500 (Which is based around Husqvarna circuit boards, etc) which is bluetooth BLE controlled via app. I'm trying the discover but haven't had time to decipher the BLE characteristics attached. Hoping to try the connect/discover (and using nRF logging) to get info and see if I can adapt a PR to help add it to this great project.

did you manage to discover something with the Flymo?
